# Generated by Django 2.1.7 on 2019-03-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedCustomers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('telegram_id', models.IntegerField(verbose_name='Telegram ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата авторизиции')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created'],
            },
        ),
    ]
